-- Push subscriptions table
create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  unique(endpoint)
);

create index if not exists idx_push_subs_user on push_subscriptions(user_id);

-- Notification log table
create table if not exists notification_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  title text not null,
  body text not null,
  random_number integer not null,
  delivered boolean not null default false,
  clicked boolean not null default false,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_notif_log_user on notification_log(user_id);

-- Enable RLS on push_subscriptions
alter table push_subscriptions enable row level security;

drop policy if exists "Users manage own subscriptions" on push_subscriptions;
create policy "Users manage own subscriptions"
  on push_subscriptions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Enable RLS on notification_log
alter table notification_log enable row level security;

drop policy if exists "Users view own notifications" on notification_log;
create policy "Users view own notifications"
  on notification_log for select
  using (auth.uid() = user_id);

-- Allow service role to insert notification_log
drop policy if exists "Service role manages notification_log" on notification_log;
create policy "Service role manages notification_log"
  on notification_log for insert
  with check (true);
